"""student active/inactive

Revision ID: 5dad0dfbbcc4
Revises: b3fd31d76abc
Create Date: 2026-09-07 15:03:11.106241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dad0dfbbcc4'
down_revision: Union[str, Sequence[str], None] = 'b3fd31d76abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('students', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone_number')
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
