"""wellness indicator

Revision ID: f4aa612a63e7
Revises: 5dad0dfbbcc4
Create Date: 2026-09-11 11:26:30.949763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4aa612a63e7'
down_revision: Union[str, Sequence[str], None] = '5dad0dfbbcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellness_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('factors_used', sa.Integer(), nullable=False),
    sa.Column('meal_factor', sa.Float(), nullable=True),
    sa.Column('emotion_factor', sa.Float(), nullable=True),
    sa.Column('veranda_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wellness_scores')
    # ### end Alembic commands ###
